-- MySQL Script generated by MySQL Workbench
-- Tue Jul 18 12:24:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optica_Cul_d'Ampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Optica_Cul_d'Ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optica_Cul_d'Ampolla` DEFAULT CHARACTER SET utf8 ;
USE `Optica_Cul_d'Ampolla` ;

-- -----------------------------------------------------
-- Table `Optica_Cul_d'Ampolla`.`Proveïdors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_d'Ampolla`.`Proveïdors` (
  `idProveïdor` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Carrer` VARCHAR(45) NOT NULL,
  `Número` INT NOT NULL,
  `Pis` INT NOT NULL,
  `Porta` VARCHAR(2) NOT NULL,
  `Codi Postal` VARCHAR(10) NOT NULL,
  `Ciutat` VARCHAR(45) NOT NULL,
  `Pais` VARCHAR(45) NOT NULL,
  `Telèfon` VARCHAR(45) NOT NULL,
  `Fax` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveïdor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_Cul_d'Ampolla`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_d'Ampolla`.`Ulleres` (
  `idUlleres` INT NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Graduació vidre dret` INT NOT NULL,
  `Graduació vidre esquerre` INT NOT NULL,
  `Tipus de montura` ENUM('flotant', 'pasta', 'metàl-lica') NOT NULL,
  `Color montura` VARCHAR(45) NOT NULL,
  `Color vidres` VARCHAR(45) NOT NULL,
  `idProveïdor` INT NOT NULL,
  `Preu` INT NOT NULL,
  PRIMARY KEY (`idUlleres`),
  INDEX `idProveïdors_idx` (`idProveïdor` ASC) VISIBLE,
  CONSTRAINT `idProveïdor`
    FOREIGN KEY (`idProveïdor`)
    REFERENCES `Optica_Cul_d'Ampolla`.`Proveïdors` (`idProveïdor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_Cul_d'Ampolla`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_d'Ampolla`.`Clients` (
  `idClient` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Adreça` VARCHAR(45) NOT NULL,
  `Telèfon` VARCHAR(45) NOT NULL,
  `Correu electrònic` VARCHAR(45) NOT NULL,
  `Date registre` DATE NOT NULL,
  `Recomenat per client` INT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `Recomenat per client_idx` (`Recomenat per client` ASC) VISIBLE,
  CONSTRAINT `Recomenat per client`
    FOREIGN KEY (`Recomenat per client`)
    REFERENCES `Optica_Cul_d'Ampolla`.`Clients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_Cul_d'Ampolla`.`Empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_d'Ampolla`.`Empleats` (
  `idEmpleat` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Cognoms` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_Cul_d'Ampolla`.`Vendes ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica_Cul_d'Ampolla`.`Vendes ulleres` (
  `idVenda` INT NOT NULL,
  `Client` INT NOT NULL,
  `Ulleres` INT NOT NULL,
  `Empleat` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `Client_idx` (`Client` ASC) VISIBLE,
  INDEX `Ulleres_idx` (`Ulleres` ASC) VISIBLE,
  INDEX `Empleat_idx` (`Empleat` ASC) VISIBLE,
  CONSTRAINT `Client`
    FOREIGN KEY (`Client`)
    REFERENCES `Optica_Cul_d'Ampolla`.`Clients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Ulleres`
    FOREIGN KEY (`Ulleres`)
    REFERENCES `Optica_Cul_d'Ampolla`.`Ulleres` (`idUlleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Empleat`
    FOREIGN KEY (`Empleat`)
    REFERENCES `Optica_Cul_d'Ampolla`.`Empleats` (`idEmpleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
